#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widget/Index.cshtml")]
    public partial class _Views_Widget_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Widget_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<h2>Test plugin</h2>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit." +
" Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Null" +
"a quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fu" +
"sce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu ege" +
"t nulla. \r\n\r\nClass aptent taciti sociosqu ad litora torquent per conubia nostra," +
" per inceptos himenaeos. Curabitur sodales ligula in libero. Sed dignissim lacin" +
"ia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at" +
" dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc e" +
"gestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, ma" +
"ssa. \r\n\r\nFusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus " +
"metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condim" +
"entum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra," +
" per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, t" +
"ortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut" +
" fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. V" +
"estibulum sapien. Proin quam. \r\n\r\nEtiam ultrices. Suspendisse in justo eu magna " +
"luctus suscipit. Sed lectus. Integer euismod lacus luctus magna. Quisque cursus," +
" metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget" +
" diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere " +
"cubilia Curae; Morbi lacinia molestie dui. Praesent blandit dolor. Sed non quam." +
" In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede facilis" +
"is laoreet. Donec lacus nunc, viverra nec, blandit vel, egestas et, augue. Vesti" +
"bulum tincidunt malesuada tellus. Ut ultrices ultrices enim. \r\n\r\nCurabitur sit a" +
"met mauris. Morbi in dui quis est pulvinar ullamcorper. Nulla facilisi. Integer " +
"lacinia sollicitudin massa. Cras metus. Sed aliquet risus a tortor. Integer id q" +
"uam. Morbi mi. Quisque nisl felis, venenatis tristique, dignissim in, ultrices s" +
"it amet, augue. Proin sodales libero eget ante. Nulla quam. Aenean laoreet. Vest" +
"ibulum nisi lectus, commodo ac, facilisis ac, ultricies eu, pede. Ut orci risus," +
" accumsan porttitor, cursus quis, aliquet eget, justo. \r\n</p>");

        }
    }
}
#pragma warning restore 1591
