#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Template/Views/Widget/Index.cshtml")]
    public partial class _Areas_Template_Views_Widget_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Template_Views_Widget_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<h3>Template</h3>\n<p>\n    Template for a basic plugin.\n</p>\n\n<p>\n    Paragraph 10" +
"1\n</p>");

        }
    }
}
#pragma warning restore 1591
